# Generated by Django 3.2.4 on 2021-06-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_auto_20210621_0539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ('visits',), 'verbose_name_plural': 'Bookmarks'},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
