# Generated by Django 3.2.4 on 2021-06-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_auto_20210623_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ('-visits',), 'verbose_name_plural': 'Bookmarks'},
        ),
    ]
